# build stage
FROM docker.io/library/node:26-alpine AS frontend-build

COPY zscaler/zscaler-root-ca.crt /tmp/zscaler-root-ca.crt

RUN apk --no-cache add --no-check-certificate ca-certificates && update-ca-certificates
RUN cat /tmp/zscaler-root-ca.crt >> /etc/ssl/certs/ca-certificates.crt
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

RUN addgroup -g 1001 -S appgroup && adduser -u 1001 -S appuser -G appgroup

RUN npm install -g npm@12.2.0

WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci  --force --loglevel verbose
COPY frontend/ .

RUN chown -R appuser:appgroup /app
USER appuser

CMD echo "Running npm audit..." && \
    npm audit --omit=dev --audit-level=high && \
    echo "Running ESLint security scan..." && \
    npx eslint "**/*.{js,mjs,cjs,vue}" --max-warnings=0