FROM docker.io/aquasec/trivy:0.74.0@sha256:62b1e65e8869bc4b4c6aa4fa2b21595256c7c2f6018a9d9ad61caf87187c1969

# copy your internal CA cert
COPY zscaler/zscaler-root-ca.crt /usr/local/share/ca-certificates/zscaler-root-ca.crt

# update trusted certificates
RUN update-ca-certificates

RUN addgroup -g 1000 appuser && adduser -D -u 1000 -G appuser appuser
USER appuser
