FROM aquasec/trivy:latest

# copy your internal CA cert
COPY zscaler/zscaler-root-ca.crt /usr/local/share/ca-certificates/zscaler-root-ca.crt

# update trusted certificates
RUN update-ca-certificates
