FROM docker.io/aquasec/trivy:0.72.0@sha256:cffe3f5161a47a6823fbd23d985795b3ed72a4c806da4c4df16266c02accdd6f

# copy your internal CA cert
COPY zscaler/zscaler-root-ca.crt /usr/local/share/ca-certificates/zscaler-root-ca.crt

# update trusted certificates
RUN update-ca-certificates

RUN addgroup -g 1000 appuser && adduser -D -u 1000 -G appuser appuser
USER appuser
