FROM docker.io/aquasec/trivy:0.72.0@sha256:7cced7cae583819fc7806d4cbc0dbbc7cad18b99f7d3e235192e6da8c091045c

# copy your internal CA cert
COPY zscaler/zscaler-root-ca.crt /usr/local/share/ca-certificates/zscaler-root-ca.crt

# update trusted certificates
RUN update-ca-certificates

RUN addgroup -g 1000 appuser && adduser -D -u 1000 -G appuser appuser
USER appuser
