FROM golang:1.24.11-alpine

COPY zscaler/zscaler-root-ca.crt /tmp/zscaler-root-ca.crt

ENV CGO_ENABLED=0
ENV GO111MODULE=on
# ENV GOPROXY=direct

RUN apk --no-cache add --no-check-certificate ca-certificates && update-ca-certificates
RUN  cp /tmp/zscaler-root-ca.crt /usr/local/share/ca-certificates/zscaler-root-ca.crt && \
      update-ca-certificates;

RUN apk update && apk add bash dos2unix git 2>/dev/null

RUN go install github.com/securego/gosec/v2/cmd/gosec@latest
RUN go install golang.org/x/vuln/cmd/govulncheck@latest

WORKDIR /app

COPY go.work* .
COPY webapi webapi
RUN go mod download


CMD echo "Running gosec..." && \
    gosec ./... && \
    echo "Running govulncheck..." && \
    cd webapi && \
    govulncheck ./...
