name: Deploy via SSH

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            cd /web/wwnmgr
            git fetch origin
            git checkout -B main origin/main
            sudo docker compose build
            echo "Build done"
            sudo systemctl restart wwnmgr
            # ungly hack while nginx is part of agentpoc and needs to be restarted to reload upstream data as docker keeps changing IPs
            sudo systemctl restart agentpoc
            echo "Systemctl restart done"
